services:
  ingest:
    image: ghcr.io/lennartkloock/bgp-hijacking-detection-ingest
    build:
      context: .
      args:
        BIN: ingest
    volumes:
      - ./local/ripe_cache:/app/local/cache
    depends_on:
      postgres:
        condition: service_started
    command: ["-o", "db_url=postgres://postgres:postgres@postgres/postgres", "-o", "log_level=info,db=debug,ingest=debug"]
    networks:
      - default
  detection:
    image: ghcr.io/lennartkloock/bgp-hijacking-detection-detection
    build:
      context: .
      args:
        BIN: detection
    depends_on:
      postgres:
        condition: service_started
    command: ["-o", "db_url=postgres://postgres:postgres@postgres/postgres", "-o", "log_level=info,db=debug,detection=debug"]
    networks:
      - default
  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - default
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - postgres:/var/lib/postgresql

networks:
  default:
    enable_ipv6: true

volumes:
  postgres:
